### ISSUE TITLE
homebrew installation error

### ISSUE THREAD

**Issue by jmgant** [jetrails/homebrew-tap#1]
following the steps to install jrctl on MacOS with homebrew creates an error. the binary is supposed to be installed below

    /opt/homebrew

there is no jrctl binary or directory anywhere under /opt/homebrew

here is some verbose output from the installation

    /opt/homebrew/Cellar/jrctl/3.2.0/bin/jrctl completion bash > /usr/local/etc/bash_completion.d/jrctl
    sh: /usr/local/etc/bash_completion.d/jrctl: No such file or directory

**Comment by null93** [comment]
Does `/usr/local/etc/bash_completion.d` exist on your system? Not sure if MacOS stopped or ever has come with `bash-completion` pre-installed but I think this might be the issue. Can you try to install bash-completions using `brew install bash-completion` and then try to install jrctl.

If this is the issue, we can either add `bash-completion` as a dependency or frankly get rid of that line all together. Considering MacOS' default shell changed to zsh anyways.

**Comment by null93** [comment]
@jmgant Was this issue resolved? Please let me know or I will mark this issue as complete.

**Comment by jmgant** [comment]
Bash completion is installed. But the directory mentioned in the error does not exist.

**Comment by null93** [comment]
So the error looks like it cannot find the `jrctl` binary. Checkout https://github.com/jetrails/homebrew-tap/blob/master/Formula/jrctl.rb#L10. I do not specify the path in the formula, I let homebrew take care if that for me.

Are you doing anything custom with homebrew? Maybe try to reinstall? It would also be interesting to see if this happens with any other formula you try to install.

**Comment by null93** [comment]
Closing, reopen if still needed.
